In [1]:
import pandas as pd
import numpy as np


#training Data

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:

train=pd.read_csv('/content/drive/MyDrive/MINI PROJECT/NEW_DATASET/TRAIN/multimodal_train.csv',sep=',')
train = train[['id','2_way_label']]
train.head()

id  2_way_label
0  awxhir            1
1  98pbid            0
2  6f2cy5            1
3  4xypkv            1
4  8gnet9            0

In [5]:
image_path = train['id']
label = train['2_way_label'].to_numpy()

In [6]:
#counting labels      

train['2_way_label'].value_counts()


0    600
1    400
Name: 2_way_label, dtype: int64

In [7]:
#IMAGE DATASET READING
import os
def loadImg(path="/content/drive/MyDrive/MINI PROJECT/NEW_DATASET/TRAIN/IMAGES"):
    return[os.path.join(path, fileName) for fileName in os.listdir(path)]
print(len(loadImg()))
loadedImageFile=loadImg()
print(len(loadedImageFile))

1000
1000


In [8]:
image_col=train['id'].tolist()

In [9]:
from PIL import Image
import cv2
import numpy as np

#SORTING OF IMAGES 
image_sort = []
for id in image_col:
  con = '/content/drive/MyDrive/MINI PROJECT/NEW_DATASET/TRAIN/IMAGES/'+id+'.jpg'
  for i in loadedImageFile:
    if(con==i):
      image_sort.append(i)

image_sort[2]

'/content/drive/MyDrive/MINI PROJECT/NEW_DATASET/TRAIN/IMAGES/6f2cy5.jpg'

In [10]:
image_read = []
for image in image_sort:
  image1 = cv2.imread(image)
  print(image1)
  #resize= cv2.resize(image1,(200,200))
  rescale=image1/ 225
  
  image_read.append(rescale)
image_array = np.asarray(image_read)

Streaming output truncated to the last 5000 lines.
  [127 139 139]]]
[[[253 253 254]
  [253 253 254]
  [253 253 254]
  ...
  [253 253 254]
  [253 253 254]
  [253 253 254]]

 [[253 253 254]
  [253 253 254]
  [253 253 254]
  ...
  [253 253 254]
  [253 253 254]
  [253 253 254]]

 [[253 253 254]
  [253 253 254]
  [253 253 254]
  ...
  [253 253 254]
  [253 253 254]
  [253 253 254]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
[[[32 28 23]
  [32 28 23]
  [32 28 23]
  ...
  [85 82 68]
  [84 81 67]
  [84 81 67]]

 [[32 28 23]
  [32 28 23]
  [32 28 23]
  ...
  [82 79 65]
  [82 78 67]
  [82 79 65]]

 [[32 29 21]
  [32 29 21]
  [32 29 21]
  ...
  [64 60 49]
  [65 60 51]
  [65 61 50]]

 ...

 [[41 34 25]
  [41 34 25]
  [42 35 26

TypeError: ignored

In [ ]:
image_array

array([array([[[175, 199, 221],
        [175, 199, 221],
        [176, 200, 222],
        ...,
        [ 70,  83, 127],
        [ 67,  80, 124],
        [ 59,  72, 116]],

       [[175, 199, 221],
        [173, 200, 221],
        [176, 200, 222],
        ...,
        [ 62,  75, 119],
        [ 66,  79, 123],
        [ 75,  88, 132]],

       [[174, 201, 221],
        [172, 202, 221],
        [174, 201, 221],
        ...,
        [ 69,  82, 126],
        [ 74,  87, 131],
        [ 83,  96, 140]],

       ...,

       [[ 60,  75, 121],
        [ 62,  77, 123],
        [ 64,  79, 125],
        ...,
        [ 31,  43,  79],
        [ 31,  43,  79],
        [ 32,  44,  80]],

       [[ 63,  78, 124],
        [ 64,  79, 125],
        [ 66,  81, 127],
        ...,
        [ 29,  41,  77],
        [ 29,  41,  77],
        [ 31,  43,  79]],

       [[ 66,  81, 127],
        [ 67,  82, 128],
        [ 69,  84, 130],
        ...,
        [ 28,  40,  76],
        [ 28,  40,  76],
        [ 29,  41

#Testing data

In [ ]:
#reading csv file
test=pd.read_csv('/content/drive/MyDrive/Ankit/EACL 2021 dec 2020/meme/testing/test_captions.csv',sep=',')
test.pop('Unnamed: 0')
test

imagename                                           captions
0      test_img_0.jpg  sugarkaga nadandhava vida figuregaga nadandhav...
1      test_img_1.jpg  i have come for my stones      stones thaane.....
2      test_img_2.jpg  "special porotta" nu pottuierukke spacial kum ...
3      test_img_3.jpg  *we : amma .. cooker 3 whistle vanthuchu off p...
4      test_img_4.jpg  creating whatsapp group - 1st day vaanga ji.. ...
..                ...                                                ...
662  test_img_662.jpg  DURING SCHOOL DAYS  ME & FRNDS: ANNA MAIL CHEC...
663  test_img_663.jpg         REMEMBER THIS KID    THIS KID IS RIGHT NOW
664  test_img_664.jpg  *SINGLES: IVAN VERA ENGALA ROMBA TORCHER PANDR...
665  test_img_665.jpg  ENAIKI PUBG LA CHICKEN DINNER VANGURA PAYALUGA...
666  test_img_666.jpg                                     LATER THAT DAY

[667 rows x 2 columns]

In [ ]:
test['captions']=test['captions'].apply(lambda x: remove_sw(x))
test['captions']=test['captions'].str.lower()       #changing into lower case       (remove and check acc too)
test['captions']=test['captions'].str.strip()       #remove white spaces
test['captions']=test['captions'].str.replace(r'\d+','')   #remove numbers
test['captions']=test['captions'].apply(lambda x: x.encode('ascii', 'ignore').decode('ascii'))  #removing emoji
test['captions']=test['captions'].str.replace('[^\w\s]','')      #removing punct


In [ ]:
encoded1 =tok1.texts_to_sequences(test['captions'])
print(test['captions'][0])
encoded1[0]

sugarkaga nadandhava vida figuregaga nadandhavan dhan adhigam


[106, 11, 398]

In [ ]:
padded = sequence.pad_sequences(encoded1, maxlen=max_length, padding='post')
padded[0]

array([106,  11, 398,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0], dtype=int32)

In [ ]:
test_image_read = []
for testimg in test['imagename']:
    print(testimg)
    image_path2= os.path.join("/content/drive/MyDrive/Ankit/EACL 2021 dec 2020/meme/testing/test_img/",testimg)
    image12 = cv2.imread(image_path2)

    dst1 = cv2.fastNlMeansDenoisingColored(image12,None,10,10,7,21)     #denoising
    image22 = cv2.resize(dst1, (200, 200))
    image32 = image22.astype('float32')
    image42 = image32/255                                      #pixels
    test_image_read.append(image42)
test_image_array = np.asarray(test_image_read)

test_img_0.jpg
test_img_1.jpg
test_img_2.jpg
test_img_3.jpg
test_img_4.jpg
test_img_5.jpg
test_img_6.jpg
test_img_7.jpg
test_img_8.jpg
test_img_9.jpg
test_img_10.jpg
test_img_11.jpg
test_img_12.jpg
test_img_13.jpg
test_img_14.jpg
test_img_15.jpg
test_img_16.jpg
test_img_17.jpg
test_img_18.jpg
test_img_19.jpg
test_img_20.jpg
test_img_21.jpg
test_img_22.jpg
test_img_23.jpg
test_img_24.jpg
test_img_25.jpg
test_img_26.jpg
test_img_27.jpg
test_img_28.jpg
test_img_29.jpg
test_img_30.jpg
test_img_31.jpg
test_img_32.jpg
test_img_33.jpg
test_img_34.jpg
test_img_35.jpg
test_img_36.jpg
test_img_37.jpg
test_img_38.jpg
test_img_39.jpg
test_img_40.jpg
test_img_41.jpg
test_img_42.jpg
test_img_43.jpg
test_img_44.jpg
test_img_45.jpg
test_img_46.jpg
test_img_47.jpg
test_img_48.jpg
test_img_49.jpg
test_img_50.jpg
test_img_51.jpg
test_img_52.jpg
test_img_53.jpg
test_img_54.jpg
test_img_55.jpg
test_img_56.jpg
test_img_57.jpg
test_img_58.jpg
test_img_59.jpg
test_img_60.jpg
test_img_61.jpg
test_img_62.jpg
te

In [ ]:
test_image_array.shape

(667, 200, 200, 3)

#model

In [ ]:
import tensorflow as tf
from keras.models import Sequential,Model
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from tensorflow.keras.layers import Conv1D, GlobalMaxPooling1D, MaxPooling1D,LSTM,Bidirectional,GlobalAveragePooling1D,Dropout, Activation, Flatten, Embedding,Input

from keras.layers.merge import concatenate

In [ ]:
#image model
# channel 0 
inputs = Input(shape=(200, 200, 3))
conv = Conv2D(filters=32, kernel_size=(3,3), activation='relu')(inputs)
pool = MaxPooling2D(pool_size=(5,5))(conv)
conv2=Conv2D(64,(3,3),activation='relu')(pool)
pool2=MaxPooling2D(pool_size=(2,2),padding='same')(conv2)
flat = Flatten()(pool2)

In [ ]:
Embedding_Layer=Embedding(input_dim = words + 1, output_dim = 300,input_length=max_length)

#text model
# channel 1
inputs1 = Input(shape=(max_length,))
embedding1 = Embedding_Layer(inputs1)
#conv1 = Conv1D(filters=32, kernel_size=2, activation='relu')(embedding1)
#drop1 = Dropout(0.5)(conv1)
#pool1 = MaxPooling1D(pool_size=2)(drop1)
lstm=Bidirectional(LSTM(128))(embedding1)
flat1 = Flatten()(lstm)

In [ ]:
#concatinate
merged = concatenate([flat1, flat])
dense1 = Dense(128, activation='relu')(merged)
outputs = Dense(2, activation='sigmoid')(dense1)
model = Model(inputs=[inputs1, inputs], outputs=outputs)
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 200, 200, 3) 0                                            
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 198, 198, 32) 896         input_1[0][0]                    
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, 30)]         0                                            
__________________________________________________________________________________________________
max_pooling2d (MaxPooling2D)    (None, 39, 39, 32)   0           conv2d[0][0]                     
______________________________________________________________________________________________

In [ ]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'Adam', metrics = ['accuracy'])

In [ ]:
model.fit([padd,image_array],label_final, epochs = 10, verbose = 1)

Epoch 1/10
72/72 [==============================] - 13s 53ms/step - loss: 0.7107 - accuracy: 0.7888
Epoch 2/10
72/72 [==============================] - 3s 47ms/step - loss: 0.0790 - accuracy: 0.9726
Epoch 3/10
72/72 [==============================] - 3s 48ms/step - loss: 0.0318 - accuracy: 0.9915
Epoch 4/10
72/72 [==============================] - 4s 49ms/step - loss: 0.0169 - accuracy: 0.9925
Epoch 5/10
72/72 [==============================] - 4s 50ms/step - loss: 0.0148 - accuracy: 0.9935
Epoch 6/10
72/72 [==============================] - 4s 50ms/step - loss: 0.0158 - accuracy: 0.9921
Epoch 7/10
72/72 [==============================] - 4s 49ms/step - loss: 0.0020 - accuracy: 0.9992
Epoch 8/10
72/72 [==============================] - 4s 49ms/step - loss: 6.9130e-04 - accuracy: 1.0000
Epoch 9/10
72/72 [==============================] - 4s 51ms/step - loss: 5.6458e-04 - accuracy: 1.0000
Epoch 10/10
72/72 [==============================] - 4s 50ms/step - loss: 3.0485e-04 - accuracy: 1.0

In [ ]:
dev_predictions = model.predict([padded,test_image_array])
# Finding out of two output neurons which one has highest probability
# It will return us the predicted class
# It will convert probability into final class 1 and 0
dev_predictions1 = np.zeros_like(dev_predictions)
dev_predictions1[np.arange(len(dev_predictions)), dev_predictions.argmax(1)] = 1

In [ ]:
lbl=pd.read_csv('/content/drive/MyDrive/Ankit/EACL 2021 dec 2020/Copy of gold_labels_for_test.csv')
lbl

Unnamed: 0       ref_caption      label
0             0    test_img_0.jpg      troll
1             1    test_img_1.jpg      troll
2             2    test_img_2.jpg      troll
3             3    test_img_3.jpg      troll
4             4    test_img_4.jpg      troll
..          ...               ...        ...
662         662  test_img_662.jpg      troll
663         663  test_img_663.jpg      troll
664         664  test_img_664.jpg      troll
665         665  test_img_665.jpg  Not_troll
666         666  test_img_666.jpg  Not_troll

[667 rows x 3 columns]

In [ ]:
val_labelEncode=labelEncode.transform(lbl['label'])
val_label=to_categorical(np.asarray(val_labelEncode))
val_label[0]

array([0., 1.], dtype=float32)

In [ ]:
#Accuracy CNN
from sklearn.metrics import classification_report
print(classification_report(val_label,dev_predictions1))

              precision    recall  f1-score   support

           0       0.52      0.06      0.10       272
           1       0.60      0.96      0.74       395

   micro avg       0.59      0.59      0.59       667
   macro avg       0.56      0.51      0.42       667
weighted avg       0.56      0.59      0.48       667
 samples avg       0.59      0.59      0.59       667



In [ ]:
#labelEncode.inverse_transform(test_predictions1).size


In [ ]:
#test['label']=labelEncode.inverse_transform(test_predictions1)
#test

In [ ]:
#test['label'].value_counts()

#Into csv


In [ ]:
#test

In [ ]:
#test[['imagename','label']].to_csv('iiit_dwd.csv',index=False)